## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

import ns3waf

def configure(conf):
    ns3waf.check_modules(conf, ['core', 'internet', 'csma'], mandatory=True)

def build(bld):
    bld.build_a_script('dce',
                       needed=['core', 'internet', 'csma', 'dce'],
                       target='bin/simulacion_hub',
                       source=['simulacion_hub.cc'],
                       )
